/*jshint esversion: 6, multistr: true, node: true*/

'use strict';

module.exports = {

  600 : "error",

  601 : "Information missing can't register",
  602 : "Unable to get user's data from EvolveChain",
  603 : "db error",
  604 : "phone or password or isd code missing" ,
  605 : "invalid username or password" ,
  606 : "Token missing" ,
  607 : "User logged in on another device-Token mismatch" ,
  608 : "Error in getting user details from the db" ,
  609 : "Failed to authenticate token" ,
  610 : "Xbook id missing" ,
  611 : "user doesn't exit" ,
  612 : "User not found" ,
  613 : "Unable to update user details" ,
  614 : "Already a friend",
  615 : "Friend request already sent",
  616 : "Friend request already received from this user",
  617 : "Hyperledger server error",
  618 : "User details not found",
  619 : "Friend request details not found",
  620 : "Friend details not found",
  621 : "Not a friend",
  622 : "No search result",
  623 : "user not logged in",
  624 : "Post Id missing",
  625 : "No likes found",
  626 : "please enter correct previous password",
  627 : "old and new password cannot be same",
  628 : "Error in adding new verified user to the db",
  629 : "Error while adding token in db",
  630 : "User details not found on HL",
  631 : "Error in uploading the profile pic",
  632 : "Error while adding profile pic path in db",
  633 : "Error in updating the user details",
  634 : "Error while sending a friend request",
  635 : "Error while getting friend request details from db",
  636 : "Error while removing a friend",
  637 : "Error while retrieving the friends list",
  638 : "Inputs missing",
  639 : "invalid isd code",
  640 : "Error in adding click details in the db",
  641 : "Error while login in",
  642 : "Error while getting user details",
  643 : "Error in adding view details in the db",
  644 : "Error while updating inventory",
  645 : "error while fetching inventory items",
  646 : "Error while monthly updation",
  647 : "Error while updating click/view price",
  648 : "Error while selecting vendor"
};
